---

resources:
- name: git-on-boarding-pipeline
  type: git
  check_every: 2m
  source:
    uri: https://github.com/blgm/on-boarding-pipeline
    branch: master

jobs:
- name: my-first-job
  plan:
  - get: git-on-boarding-pipeline
  - task: our-task
    file: git-on-boarding-pipeline/task.yml
